### ISSUE TITLE
Project overview, purpose and scope

### ISSUE THREAD

**Issue by richardsj** [esphome/home-assistant-voice-pe#203]
The description of the purpose, proposed functionality, skills needed (hardware or just software) and state of development are missing. Instead the Github page for this project just shows the Code of Conduct.

It appears to be a self-sufficient satellite with local micro model for the wakeword, and something to do with ESPHome hardware.

The vision might be exciting, encourage others to get involved!

**Comment by Hedda** [comment]
+1, the Nabu Casa's devs are still [in-company stealth mode](https://en.wikipedia.org/wiki/Stealth_mode) about this and trying to keep details on the "voice satellite" hardware as secret as possible until it is time to be released, (the drawbacks/downsides to working in stealth mode on an open-source project like this is that it limits feedback and prevents the building of pre-launch buzz/excitement before this project and/or product is made more public, while if this development would instead be made more in the open then the community members could come with input and contribute code. However, home things about that new hardware can be gleaned elsewhere or be deduced from the features and functions already added here and to Home Assistant core so far. You can find my inofficial summary about it here:

* https://github.com/esphome/home-assistant-voice-pe/issues/52

FYI, Home Assistant's core developers have each month during the last few Release Parties videos been giving several not-so-subtle verbal hints that some kind of official Home Assistant "voice satellite" hardware based on ESPHome is not only in the works by Nabu Casa developers but that Home Assistant branded "voice satellite" hardware is likely to be released relatively soon, though there are no details yet if that first "voice satellite" hardware to be released only be more of a ESPHome voice development kit or more of a finished retail product with "[Home Approval Factor](https://newsletter.openhomefoundation.org/open-home-approval-factor/)" and carrying the Home Assistant brand, so keep watching the official Home Assistant and Open Home Foundation channels for more detailed news to hopefully come soon:

* https://www.youtube.com/@home_assistant
* https://www.home-assistant.io/blog/
* https://newsletter.openhomefoundation.org/

Anyway, if you are a developer or an advanced tinkerer who can not wait and wants to try this code/project today on similar development hardware to what is used to develop this then suggest check out the “ReSpeaker Lite” discussion in Home Assistant's community forum here -> https://community.home-assistant.io/t/respeaker-lite-new-seeed-studio-voice-assistant-development-kit-hardware-combine-esp32-with-xmos-xu316-dsp-chip-for-advanced-audio-processing-as-a-esphome-based-home-assistant-assist-satellite-voice-devkit/756944

**Comment by balloob** [comment]
Keep an eye out on the Home Assistant blog to learn more soon!
