### ISSUE TITLE
Feature Request: Select HA Media Player Entity as default Speaker 

### ISSUE THREAD

**Issue by bluenazgul** [esphome/home-assistant-voice-pe#231]
Like it is possible on Amazon Echo Devices and Google Home / Google Nest Devices it would be great to be able to select an Media Player via HA the is the default Speaker for the Voice PE

This way it would be possible to select e.g. an Sonos Speaker that is allready the Rooms default Speaker and dont has 3,5mm input Andre Schlüter Speaker for the Voice PE

**Comment by balloob** [comment]
Thanks for the feedback. This would actually be a feature that Home Assistant would need to add, not something the VPE could add. 

Feature requests can be added in the HA forums: https://community.home-assistant.io/c/feature-requests/13

**Comment by Plawasan** [comment]
> Thanks for the feedback. This would actually be a feature that Home Assistant would need to add, not something the VPE could add.
> 
> Feature requests can be added in the HA forums: https://community.home-assistant.io/c/feature-requests/13

Would it not be possible directly from ESPhome? I've seen this method used by a different project:

![image](https://github.com/user-attachments/assets/18581219-5932-4528-aaff-160e80024f53)
