### ISSUE TITLE
Home assistant Voice PE TLS certificate verification failed

### ISSUE THREAD

**Issue by limitless-code** [esphome/home-assistant-voice-pe#238]
Hello. 

I have purchased HA Voice Preview edition and added the device to HASSIO core 2024.12.5. some features work but TTS responses do not.

When I select "set up voice assistant" in integrations > ESPHome

After awhile I see the following:

"The voice assistant is unable to connect to Home Assistant
To play audio, the voice assistant device has to connect to Home Assistant to fetch the files. Our test shows that the device is unable to reach the Home Assistant server." 

After some troubleshooting and not getting very far I decided to "Take control" using "ESPHome builder".

After compiling and installing, I see the following in the logs.

```
[23:45:15][D][esp-idf:000][ann_read]: E (2819428) esp-x509-crt-bundle: Failed to verify certificate

[23:45:15][D][esp-idf:000][ann_read]: E (2819431) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x3000

[23:45:15][D][esp-idf:000][ann_read]: E (2819432) esp-tls: Failed to open new connection

[23:45:15][D][esp-idf:000][ann_read]: E (2819433) transport_base: Failed to open a new connection

[23:45:15][D][esp-idf:000][ann_read]: E (2819434) HTTP_CLIENT: Connection failed, sock < 0

[23:45:15][E][nabu_media_player.pipeline:171]: Media reader encountered an error: ESP_ERR_HTTP_CONNECT
[23:45:15][E][nabu_media_player:305]: The announcement pipeline's file reader encountered an error.
```
It seems perhaps the "unable to connect to home assistant to play voice" error may be due to a certificate error? 

Is there a way to get round this problem? Perhaps an ignore SSL error configuration entry or ideally add the appropriate root CA to the bundle? If that is the cause? I believe it is a self-signed certificate.

Commands such as "turn the light on" or off do work, just responses to things like "what time is it?" Or the audio response to successfully turning the light off are not audible. There's no audio from TTS but I can see the text response in the logs using ESPHome builder and connecting via WiFi to see the log output.

Your input is very much appreciated.

**Comment by kahrendt** [comment]
The media player does support validating certificates, but not all certificate types are supported. For example, it doesn't support TLS1.3 certificates due to a limitation from the esp-tls library.

**Comment by limitless-code** [comment]
> The media player does support validating certificates, but not all certificate types are supported. For example, it doesn't support TLS1.3 certificates due to a limitation from the esp-tls library.

Thank you for your input.

![Screenshot_2024-12-24-16-58-00-440-edit_com android chrome](https://github.com/user-attachments/assets/a28bb21a-4a6f-42ce-833e-1de09a762b8b)

It is indeed using TLS1.3. Will downgrading the certificate to TLS1.2 work for a self signed certificate on HA on HA Voice PE? Would a configuration to ignore (not ideal I know) warnings etc work as a work around and is there such an available configuration option in ESPHome builder?

**Comment by kahrendt** [comment]
Downgrading should work. The ESP32 either universally ignores or universally validates certificates. For audio, it is probably not an issue to ignore the certificate, but it is also used when we check for new firmware updates where it is very important. If you take control of the device in the ESPHome builder, then you won't need to check for firmware updates, so I believe you can set it to ignore validating, but I haven't tested this. 

I think this should work: add an ``http_request`` component and set ``verify_ssl: false``. The ``nabu`` media player should follow the configuration settings in the ``http_request`` component.

**Comment by limitless-code** [comment]
You are correct

Adding...

```
http_request:
   verify_ssl: false
```

To the ESPHome builder configuration of the device,
stops the device verifying the TLS certificate. As I have self-signed the certificate this is the quickest way to a work around. Pity there isn't a way to specify the host URLs, there seems to be a way for action > http_request.get and post but not http_request from what I can see.

The other more preferred method would be to recreate the certificate with TLS1.2 and then add the root CA to the bundle that is on the esp32 device not sure how to add the bundle to the device.

At least it is working now and something for everyone at home to play with over Xmas.

Many thanks for your help!

**Comment by abliss** [comment]
I also have TLS1.3.  i believe I followed the instructions at https://community.home-assistant.io/t/how-to-configure-lets-encrypt-ssl-certificates-for-home-assistant-completely-100-free-updated-for-2022-2023/508329 to use the letsencrypt addon .  Perhaps that should be changed to use tls1.2 by default

**Comment by davidjmeier** [comment]
Thank you for posting the workaround here.  Can we please get this in official documentation and potentially as part of the onboarding sequence?  For those of us who have an appropriately deployed local implementation (only local certs to access HA) this breaks in very unfortunate ways - meaning that the device will work sporadically, but is not reliable.  This gives the impression to the end user that something else may be wrong and the certificate may not actually be the issue.  Getting to a point where seeing the actual error is quite a bit of work for a less seasoned end user which will cause frustration.

I definitely did not expect the certificate version (TLS1.3) to be the issue at all given how the device was reacting (and not).  It may be due to the fact that I also subscribe to HA Cloud and maybe the device was somehow flipping between trying to access locally and via cloud?  Not exactly sure, but hopefully this gets resolved and we can get TLS1.3 certs validated with no workarounds in the future.

Appreciate all of the insight in the thread here!

**Comment by Stephan-4711** [comment]
Is there a way to set ssl verify to false without taking control with esphome? I can't find a corresponding yaml to set this and in homeassistant it self there eis no option to ignore the certificate

**Comment by ordex** [comment]
> Is there a way to set ssl verify to false without taking control with esphome? I can't find a corresponding yaml to set this and in homeassistant it self there eis no option to ignore the certificate

there is none as far as I know.
My only way out, so far, was to change the Local URL in the network settings to point to the non-HTTPS HA endpoint.
In my case it is the original http://myhomeassistant.something:8123

This way the PE will work and not use TLS for the time being.

The ultimate approach to fixing this issue is not to skip TLS verification entirely, but having a way to side load our own CA onto the PE. This way the local cert can be verified and PE would be happy.

**Comment by limitless-code** [comment]
@davidjmeier @kahrendt Hello please see this issue I have tested and looks to me that self-signed certificates no longer have to have the work around of `verify_ssl: false`, this was less than ideal. We can now add our own rootCA.crt so our self-signed certificates can be verified.

https://github.com/esphome/esphome/issues/13551

**Comment by ordex** [comment]
Cool!
Having the possibility to add a custom CA.
This is exactly the fix that we were waiting for! 

How can this seeing now be exposed to the HA UI?

**Comment by limitless-code** [comment]
@ordex I have created a new issue with espHome here:

https://github.com/esphome/esphome/issues/13575

Feel free to comment etc as perhaps I haven't explained properly or it's not the right integration to target a solution but I am optimistic.

**Comment by Stephan-4711** [comment]
My problem happens with a public cert from let's encrypt. I cant see how this will help?

**Comment by ordex** [comment]
> My problem happens with a public cert from let's encrypt. I cant see how this will help? 

This is weird and it should not happen, unless you have a very very old firmware.

Therefore it may just be a different issue.

**Comment by limitless-code** [comment]
@Stephan-4711 I agree with @ordex I don't run letsencypt so can't test, but I presume that the root CA certificate is included in the firmware unless there are memory constraints with including all possible certificate authority certificates. If it is not this sounds like the certificate or the certificate chain is not valid. If your HA environment is externally accessible try test your current setup with and SSL checker tool such as:

https://www.ssllabs.com/ssltest/

Or you could try setting it up with a self-signed certificate setup. Here is the method I used in it's entirety. There's tests in the below link that you can use to check your certificate chain using openSSL if you are not comfortable checking using a checker on some random website.

https://github.com/esphome/esphome/issues/13551#issuecomment-3806000796

**Comment by Stephan-4711** [comment]
when I first replied here in oct. there was no way to use my dns name for internal hostname. I will need to retest the setup process

**Comment by limitless-code** [comment]
@Stephan-4711 I think that is why I ended up using a self-signed certificate as letsencypt was not able to renew the certificate every year (from memory) if you're HA server was not publicly/ externally exposed on the internet (there may be ways around this using scripts).

You could try using a combination of self-signed SSL certificate and CA and the zerotier addon to access your HA from the internet. If you use Nabu Casa (I am not familiar with this setup) this suggestion will not help.

You can add your public fqdn to your internal DNS resolver/ server so it points to your internal IP address for HA, this will allow traffic to route to your HA server on your LAN when you access or any other device access it via your LAN including your voice PE device. 

Also if you have multiple DNS names for your HA setup (external and internal) you may need to add SANs to your SSL certificate. More details are in the link in my previous comment.

**Comment by Stephan-4711** [comment]
@limitless-code my reverseproxy with split dns is configured fine. thanks for your recommendation.

**Comment by ordex** [comment]
> You can add your public fqdn to your internal DNS resolver/ server so it points to your internal IP address for HA, this will allow traffic to route to your HA server on your LAN when you access or any other device access it via your LAN including your voice PE device.

I do exactly this.
The same hostname resolves to my public IP address from the outside, but it resolves to my private IP when I am inside the LAN. My HA instance is then exposed to the internet via one port forwarding.

This way the same hostname works all the time.

Bonus: if you use IPv6 you can use the same IP no matter what :-)

**Comment by limitless-code** [comment]
Setting `verify_ssl: false` is less than ideal and NOT SECURE as disabling verify_ssl does not only apply to your HA web host but applies to all web hosts the voice PE packages yaml is configured to require (I believe this to correct) and there are many packages FROM THE INTERNET it needs to compile. So setting `verify_ssl: false` is an absolute last resort and I believe most if not all issues regarding SSL certificates not verifying should be resolved. I can only see certificate chain issues being a problem (not having the complete chain configured or bundled properly) or certificates having expired. If it is failing post your voice PE device debug logs redacting any private information.

**Comment by limitless-code** [comment]
@Stephan-4711 please check the following issues I described here, hope it helps: 

https://github.com/esphome/home-assistant-voice-pe/issues/536#issuecomment-3811681410
