### ISSUE TITLE
My work on the audio components.

### ISSUE THREAD

**Issue by nielsnl68** [esphome/home-assistant-voice-pe#34]
For my combadge project i started to make changes so i could make create a nice working intercom/walky-talky component.

I like to donate that work to the esphome project and i just was pointing to this project by Jesse. 
I think commit it here would be better. But not sure to which branch i should commit the changes.
Here are some PR's that i already committed:
https://github.com/esphome/esphome/pull/7183
https://github.com/esphome/esphome/pull/7137
https://github.com/esphome/esphome/pull/6817

Also you can find more changes on my privé and business branches.
https://github.com/nielsnl68/esphome/branches
https://github.com/lumenSoftNL/combadge

Let me know how i can assist with your work? :D

**Comment by balloob** [comment]
Going to close this issue. Instead, we're working on moving the components in this repo upstream.
